### ISSUE TITLE
Create new NPM releases

### ISSUE THREAD

**Issue by tdnguyen6** [Gyumeijie/download-from-github#11]
Please consider release a new version on npm with the updated dependencies and code.

**Comment by Gyumeijie** [comment]
Okay, I will make it several days later.

**Comment by tdnguyen6** [comment]
Seems like there is still no new release. You can add me as a collaborator on npm so I can help you make a new release. I need this package on several new setup.

**Comment by Gyumeijie** [comment]
sorry, I try several times logining my npm account but still failed, so I can't publish a new release, neither to invite you as a  collaborator on npm.
en..., If you need this package for some use, you can publish you own npm pacakge using this repository. 
sorry again, I don't use npm for almost two years, so I can't fix it in a short time

**Comment by tdnguyen6** [comment]
Here is the new npm package I published, for anyone who might need:
https://www.npmjs.com/package/@tidunguyen/github-files-fetcher

**Comment by Gyumeijie** [comment]
thanks tidunguyen @tidunguyen
